"""
Omni-Help — Live LangSmith Trace Runner
========================================
Run this script to fire a real graph execution and see the full X-Ray trace
in your LangSmith dashboard: every node, every LLM call, token usage, latency.

CRITICAL ORDERING RULE
-----------------------
LangSmith tracing is activated when LangChain is *imported*, not when the LLM
is called. This means load_dotenv() MUST run before any `from langchain*`
or `from graph.*` import. All heavy imports are therefore deferred inside
run_trace() to guarantee the environment is populated first.

Run from the repo root (venv activated):
    python src/utils/live_trace.py
"""

import asyncio
import os
import sys

# ---------------------------------------------------------------------------
# Step 0: Load .env FIRST — before any LangChain import touches the env vars
# ---------------------------------------------------------------------------
from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Step 1: Sanity-check LangSmith configuration
# ---------------------------------------------------------------------------

TRACING_ACTIVE = os.getenv("LANGCHAIN_TRACING_V2", "false").strip().lower() == "true"
LANGSMITH_KEY   = os.getenv("LANGCHAIN_API_KEY", "").strip()
LANGSMITH_PROJECT = os.getenv("LANGCHAIN_PROJECT", "omni-help").strip()

BANNER = "=" * 68

def _check_env() -> bool:
    """
    Verify that LangSmith is properly configured.

    Returns:
        True if all required variables are set and tracing is enabled.
        Prints a loud warning and returns False otherwise.
    """
    issues = []

    if not TRACING_ACTIVE:
        issues.append(
            "  ✗  LANGCHAIN_TRACING_V2 is not 'true'\n"
            "     → Open your .env file and change the line to:\n"
            "         LANGCHAIN_TRACING_V2=true"
        )

    if not LANGSMITH_KEY:
        issues.append(
            "  ✗  LANGCHAIN_API_KEY is empty\n"
            "     → Get your key at https://smith.langchain.com/settings\n"
            "     → Add it to .env: LANGCHAIN_API_KEY=lsv2_pt_..."
        )

    if issues:
        print(f"\n{BANNER}")
        print("⚠️  LANGSMITH TRACING IS NOT ACTIVE — ABORTING")
        print(BANNER)
        for issue in issues:
            print(issue)
        print(f"\n{BANNER}")
        print("Fix the issues above, then re-run:")
        print("  python src/utils/live_trace.py")
        print(BANNER + "\n")
        return False

    print(f"\n{BANNER}")
    print("✅ LangSmith tracing is ENABLED")
    print(f"   Project : {LANGSMITH_PROJECT}")
    print(f"   Key     : {LANGSMITH_KEY[:12]}... (truncated)")
    print(f"   Dashboard: https://smith.langchain.com/")
    print(BANNER + "\n")
    return True


# ---------------------------------------------------------------------------
# Step 2: The trace runner
# ---------------------------------------------------------------------------

# These two queries are designed to force different routing paths and make
# the LangSmith trace as rich as possible to explore:
#   - A combined policy + order question → router picks one intent, but the
#     full classification chain (confidence scoring, rationale) is still traced
#   - A follow-up order lookup → exercises the SQL pipeline
TRACE_QUERIES = [
    (
        "I need to know the return policy for electronics, and also, "
        "where is my order ORD-1001? It was supposed to arrive last week.",
        "Multi-intent query — router must choose and commit to one path",
    ),
    (
        "What is the shipping carrier for order ORD-1002?",
        "Direct SQL query — exercises NL→SQL generation and FR-015 guardrail",
    ),
]


async def run_trace() -> None:
    """
    Execute the Omni-Help graph with two representative queries and print
    the results. Each invocation produces one LangSmith trace run.

    The traces will appear in your LangSmith project under the run names
    generated by LangGraph (one per ainvoke call).
    """
    # Deferred imports — LangSmith hooks into LangChain at import time,
    # so load_dotenv() must already have run before these lines execute.
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
    from graph.graph import build_graph  # noqa: PLC0415

    print("Compiling LangGraph...")
    omni_graph = build_graph()
    print("Graph compiled. Starting trace runs...\n")

    for i, (query, description) in enumerate(TRACE_QUERIES, start=1):
        print(f"{BANNER}")
        print(f"Run {i}/{len(TRACE_QUERIES)}: {description}")
        print(f"Query: \"{query}\"")
        print(BANNER)

        try:
            result = await omni_graph.ainvoke(
                {"user_query": query},
                config={
                    "configurable": {"thread_id": f"live-trace-run-{i}"},
                    # run_name appears as the trace title in the LangSmith UI
                    "run_name": f"live_trace_run_{i}",
                    "tags": ["live-trace", "manual-test"],
                    "metadata": {
                        "test_description": description,
                        "script": "src/utils/live_trace.py",
                    },
                },
            )

            intent    = result.get("intent", "unknown")
            confidence = result.get("confidence", 0.0)
            response  = result.get("final_response", "(no response)")

            print(f"\n  Intent     : {intent}")
            print(f"  Confidence : {confidence:.0%}")
            print(f"  Response   : {response[:300]}{'...' if len(response) > 300 else ''}\n")

        except Exception as exc:
            print(f"\n  ❌ Run {i} failed: {exc}\n")

    # ---------------------------------------------------------------------------
    # Step 3: Closing banner
    # ---------------------------------------------------------------------------
    print(BANNER)
    print("✅  Run complete!")
    print()
    print("   Open your LangSmith dashboard to view:")
    print("   → Full execution trace (every node, conditional edge, LLM call)")
    print("   → Per-node latency breakdown")
    print("   → Token usage and model metadata")
    print("   → Inputs and outputs at each step")
    print()
    print("   Dashboard : https://smith.langchain.com/")
    print(f"   Project   : {LANGSMITH_PROJECT}")
    print("   Filter    : tags = 'live-trace'")
    print(BANNER + "\n")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    if not _check_env():
        sys.exit(1)

    asyncio.run(run_trace())
