"""
Secure SQL tool for the Omni-Help Order Management pipeline.

Wraps SQLite access behind two critical enterprise guardrails:

  1. Read-only enforcement (FR-015): validate_read_only_sql() rejects any
     mutation keyword (DROP, DELETE, UPDATE, INSERT, ALTER) before execution.

  2. Single-connection abstraction: the rest of the codebase imports
     execute_secure_query() and get_schema() — never SQLAlchemy directly.
     Swapping SQLite for PostgreSQL only requires changes to this file.

Usage:
    from tools.sql_db import execute_secure_query, get_schema

    schema = get_schema()
    rows   = execute_secure_query("SELECT * FROM orders WHERE order_id = 'ORD-1001'")
"""

import re
from typing import Any

from langchain_community.utilities import SQLDatabase

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DB_URI = "sqlite:///data/db/orders.db"

# Mutation keywords that are never permitted (FR-015)
_FORBIDDEN_KEYWORDS = re.compile(
    r"\b(DROP|DELETE|UPDATE|INSERT|ALTER|TRUNCATE|REPLACE|MERGE|CREATE|GRANT|REVOKE)\b",
    re.IGNORECASE,
)

# ---------------------------------------------------------------------------
# Singleton DB connection — opened once at module load, reused per call.
# ---------------------------------------------------------------------------

_db: SQLDatabase | None = None


def _get_db() -> SQLDatabase:
    """
    Return the singleton SQLDatabase instance, initialising it on first call.

    Returns:
        LangChain SQLDatabase connected to the local SQLite orders database.

    Raises:
        FileNotFoundError: If the database file has not been created yet.
    """
    global _db
    if _db is None:
        import os
        db_path = DB_URI.replace("sqlite:///", "")
        if not os.path.isfile(db_path):
            raise FileNotFoundError(
                f"Orders database not found at '{db_path}'. "
                "Run the init script first: python src/utils/init_db.py"
            )
        _db = SQLDatabase.from_uri(DB_URI)
    return _db


# ---------------------------------------------------------------------------
# Guardrail: FR-015 — read-only enforcement
# ---------------------------------------------------------------------------

def validate_read_only_sql(query: str) -> None:
    """
    Reject any SQL that contains data-mutation or schema-mutation keywords.

    This is the primary security boundary of the SQL pipeline. Even if the
    NL→SQL LLM generates a destructive query, it will be stopped here before
    it reaches the database.

    Args:
        query: Raw SQL string generated by the LLM.

    Raises:
        ValueError: If the query contains a forbidden keyword, with the
            offending keyword named in the error message.

    Example:
        >>> validate_read_only_sql("DROP TABLE orders")
        ValueError: Forbidden SQL operation detected: 'DROP'. Only SELECT queries are permitted.

        >>> validate_read_only_sql("SELECT * FROM orders")
        # passes silently
    """
    match = _FORBIDDEN_KEYWORDS.search(query)
    if match:
        raise ValueError(
            f"Forbidden SQL operation detected: '{match.group().upper()}'. "
            "Only SELECT queries are permitted."
        )


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------

def execute_secure_query(query: str) -> Any:
    """
    Validate and execute a read-only SQL query against the orders database.

    Runs validate_read_only_sql() before touching the database. On success,
    returns the raw result string from LangChain's SQLDatabase. On validation
    failure, propagates the ValueError to the caller so the sql_node can
    write it to sql_error in AgentState.

    Args:
        query: SQL SELECT string, typically generated by the NL→SQL LLM.

    Returns:
        Query result as a string (rows formatted by LangChain SQLDatabase).

    Raises:
        ValueError: If the query contains a forbidden keyword (FR-015).

    Example:
        >>> result = execute_secure_query("SELECT * FROM orders LIMIT 3")
        >>> print(result)
        [('ORD-1001', 'alice@example.com', 'Shipped', 129.99, '2025-...'), ...]
    """
    validate_read_only_sql(query)
    db = _get_db()
    return db.run(query)


def get_schema() -> str:
    """
    Return the database schema as a human-readable string.

    The schema is injected into the NL→SQL system prompt so the LLM
    knows the exact table and column names before generating SQL.

    Returns:
        String describing all tables and their columns.

    Example:
        >>> print(get_schema())
        CREATE TABLE orders (
            order_id TEXT ...
        )
        ...
    """
    return _get_db().get_table_info()
